version: "2"
services:
  vpn:
    image: matthewbaggett/openvpn-2fa-automator
    build: .
    cap_add:
      - net_admin
    restart: unless-stopped
    security_opt:
      - label:disable
    privileged: true
    volumes:
      - /dev/net:/dev/net:z
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/screen:/var/run/screen
      - .:/scripts
